/**
 * 外研社（新版）四年级下册 英语单词库
 * 按 Unit 分单元，严格按照教材
 */
const WORD_DATA = {
  'Unit 1': [
    { en: 'doctor', cn: '医生，大夫' },
    { en: 'fireman', cn: '消防队员' },
    { en: 'farmer', cn: '农民；农场主' },
    { en: 'cook', cn: '厨师，炊事员' },
    { en: 'police', cn: '警察' },
    { en: 'police officer', cn: '警察，警官' },
    { en: 'station', cn: '所；站；台；局' },
    { en: 'police station', cn: '警察局，派出所' },
    { en: 'often', cn: '经常，时常' },
    { en: 'field', cn: '田地，田野' },
    { en: 'painter', cn: '画家' },
    { en: 'use', cn: '用，使用' },
    { en: 'brush', cn: '刷子；毛刷' },
    { en: 'scientist', cn: '科学家' },
    { en: 'writer', cn: '作家；作者' },
    { en: 'worker', cn: '工人' },
    { en: 'aunt', cn: '姑母；姨母' },
    { en: 'night', cn: '夜晚，夜间' },
    { en: 'owl', cn: '猫头鹰' },
    { en: 'night owl', cn: '夜猫子，喜欢熬夜的人' },
    { en: 'driver', cn: '司机，驾驶员' },
    { en: 'taxi', cn: '出租车，计程车' },
    { en: 'safe', cn: '安全的，没有危险的' },
    { en: 'nurse', cn: '护士' },
    { en: 'light', cn: '照亮' },
    { en: 'uncle', cn: '叔叔，伯伯' },
    { en: 'bake', cn: '烘，烤，焙' },
    { en: 'bee', cn: '蜜蜂' },
    { en: 'same', cn: '相同的，一模一样的' },
    { en: 'sound', cn: '声，声音' },
    { en: 'postman', cn: '邮递员' },
    { en: 'life', cn: '生活' },
    { en: 'mountain', cn: '高山' }
  ],
  'Unit 2': [
    { en: 'laugh', cn: '发出笑声，大笑' },
    { en: 'sad', cn: '不愉快的，伤心的' },
    { en: 'scared', cn: '害怕的，恐惧的' },
    { en: 'angry', cn: '发怒的，生气的' },
    { en: 'excited', cn: '兴奋的，激动的' },
    { en: 'opera', cn: '歌剧' },
    { en: 'next', cn: '紧接着的；下次的' },
    { en: 'cough', cn: '咳嗽，咳' },
    { en: 'better', cn: '好转的；减轻的' },
    { en: 'gift', cn: '礼物' },
    { en: 'model', cn: '模型' },
    { en: 'shout', cn: '大声说，喊叫' },
    { en: 'should', cn: '应当，应该' },
    { en: 'feeling', cn: '感觉，感触' },
    { en: 'huge', cn: '巨大的' },
    { en: 'worried', cn: '担心的，焦虑的' },
    { en: 'street', cn: '大街，街道' },
    { en: 'hit', cn: '撞击，碰撞' }
  ],
  'Unit 3': [
    { en: 'talent', cn: '天资，天赋，才能' },
    { en: 'act', cn: '演出；扮演' },
    { en: 'magic', cn: '魔术，戏法' },
    { en: 'shine', cn: '表现突出，出众' },
    { en: 'puzzle', cn: '拼图游戏' },
    { en: 'dancer', cn: '舞蹈演员' },
    { en: 'win', cn: '获胜，赢' },
    { en: 'just', cn: '就，只是' },
    { en: 'boy', cn: '男孩；儿子' },
    { en: 'slowly', cn: '缓慢地，慢慢地' }
  ],
  'Unit 4': [
    { en: 'seed', cn: '种子，籽' },
    { en: 'earth', cn: '泥土，土壤' },
    { en: 'root', cn: '根' },
    { en: 'stem', cn: '茎，梗，柄' },
    { en: 'thin', cn: '细的' },
    { en: 'leaf', cn: '叶，叶子' },
    { en: 'dig', cn: '挖，掘' },
    { en: 'sunflower', cn: '向日葵' },
    { en: 'plant', cn: '种植，栽种；播种' },
    { en: 'dream', cn: '梦想，愿望，理想' },
    { en: 'sleep', cn: '睡，睡觉' },
    { en: 'will', cn: '将，会，要' },
    { en: 'true', cn: '真的，真实的' },
    { en: 'come true', cn: '实现' },
    { en: 'paper', cn: '纸' }
  ],
  'Unit 5': [
    { en: 'drama', cn: '戏剧' },
    { en: 'trip', cn: '旅游；旅行' },
    { en: 'fair', cn: '集市；义卖会' },
    { en: 'festival', cn: '节，节庆，汇演' },
    { en: 'horn', cn: '角' },
    { en: 'dot', cn: '点，小圆点' },
    { en: 'raindrop', cn: '雨点，雨滴' },
    { en: 'more', cn: '更多的' },
    { en: 'special', cn: '特殊的，特别的' },
    { en: 'keeper', cn: '看守人，保管人' },
    { en: 'hey', cn: '嘿，喂' },
    { en: 'lovely', cn: '美好的；可爱的' },
    { en: 'student', cn: '学生' },
    { en: 'culture', cn: '文化' },
    { en: 'hour', cn: '小时' },
    { en: 'note', cn: '笔记，记录' },
    { en: 'vote', cn: '选票' },
    { en: 'design', cn: '设计' },
    { en: 'hometown', cn: '家乡，故乡' }
  ],
  'Unit 6': [
    { en: 'T-shirt', cn: 'T恤衫' },
    { en: 'skirt', cn: '半身裙，裙子' },
    { en: 'shorts', cn: '短裤' },
    { en: 'shirt', cn: '衬衫' },
    { en: 'trousers', cn: '裤子' },
    { en: 'scarf', cn: '围巾' },
    { en: 'sweater', cn: '毛线衣，针织衫' },
    { en: 'dress', cn: '连衣裙' },
    { en: 'party', cn: '聚会，宴会' },
    { en: 'dressmaker', cn: '裁缝' },
    { en: 'wrong', cn: '不正确的，错误的' },
    { en: 'clever', cn: '聪明的' },
    { en: 'whale', cn: '鲸' },
    { en: 'Mr', cn: '先生' },
    { en: 'uniform', cn: '制服' },
    { en: 'robe', cn: '长袍' }
  ]
};
